### PR TITLE
timetracker: leagues botanist relic time tracking

### PR DESCRIPTION
**Pull request by AzOSRS**

### CODE REVIEW

**Review by MadCatzAno — APPROVED** [review]
Tested with tomatoes and potatoes. Simple math with the 5× rate.
LGTM!

**Comment by AzOSRS** [comment]
ignore these 4 commits, I'm stupid and forgot to use branches

**Review by MadCatzAno — APPROVED** [review]
Same as the last one.
LGTM.

**Comment by xKylee** [comment]
should probably have a world check also, incase the varbit gets reused

**Pull request closed without merging**
