### PR TITLE
Food collecter at ardy bank for knights

### PR DESCRIPTION
**Pull request by dragoncla**
can you add an automatic food collector at ardougne bank for when pickpocketing knights? (auto thiever)

### CODE REVIEW

**Comment by xKylee** [comment]
Retard

**Comment by dragoncla** [comment]
how is that retarded? for asking if he can script a food withdrawal from the bank to make it completely automated??

**Comment by grian32** [comment]
apologies @dragoncla youre not a retard, that would be an insult to retards
youre just missing a brain ,like the space where the brain goes in your body is just empty space

**Comment by dragoncla** [comment]
im so confused as to how its retarded to ask to withdraw food from the bank?

**Comment by dragoncla** [comment]
if the bet can eat the food ID, surely its not impossible to withdraw the same ID from the bank?

**Comment by grian32** [comment]
as i said in my last reply, you're not retarded, as that would be an insult to retards, you are missing a brain though, which is the reason you can't comprehend why kyle called you a retard

**Comment by grian32** [comment]
you don't need to understand coding to understand why kyle called you a retard

**Comment by Nan0bit** [comment]
@grian32 man ur really giving people with no brain the short end of the stick here; I think this retard has a black hole in his cranium

**Comment by grian32** [comment]
_>man ur really giving people with no brain the short end of the stick here
true
_>black hole in his cranium
perhaps, definetly a possibility regarding him

**Comment by dragoncla** [comment]
since then, i must be a retard, please enlighten me as to why my suggestion was so retarded

**Comment by Nan0bit** [comment]
why are you trying to merge 155 unethical commits and asking for more unethical features in my moral christian repo

**Comment by dragoncla** [comment]
so in other words, doing so will surely get a ban. gotcha.

**Comment by Nan0bit** [comment]
t h i s   i s   t h e   w r o n g   r e p o

**Comment by Tjechi** [comment]
No, the reason is that you're trying to do something that is against the terms of service of the game. We don't support any automation or anything that is against the TOS of Jagex.

**Comment by Tjechi** [comment]
> t h i s     i s     t h e     w r o n g     r e p o
> a m o n g     o t h e r     t h i n g s

**Comment by dragoncla** [comment]
im such a retard

**Comment by Nan0bit** [comment]
yes

**Comment by grian32** [comment]
> im such a retard

yes, this is true

**Comment by dragoncla** [comment]
im glad we can all agree

**Comment by Tjechi** [comment]
Thank you for your understanding. Have a good day.

**Pull request closed without merging**
